/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About_us: typeof import('./src/components/about_us.vue')['default']
    Advantages: typeof import('./src/components/advantages.vue')['default']
    Benefits: typeof import('./src/components/benefits.vue')['default']
    First_page: typeof import('./src/components/first_page.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home_page: typeof import('./src/components/home_page.vue')['default']
    Nav_bar: typeof import('./src/components/nav_bar.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Navigation_bar: typeof import('./src/components/navigation_bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
